### ISSUE TITLE
registration broken

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#297]
java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/AbstractPutObjectRequest
        at aws.sdk.s3$__GT_PutObjectRequest.invoke(s3.clj:183)
        at aws.sdk.s3$put_object.doInvoke(s3.clj:214)
        at clojure.lang.RestFn.invoke(RestFn.java:497)
        at chat.server.invite$upload_avatar.invoke(invite.clj:174)
        at chat.server.handler$fn__71.invoke(handler.clj:47)
        at compojure.core$make_route$fn__1779.invoke(core.clj:130)
        at compojure.core$wrap_route_middleware$fn__1775.invoke(core.clj:118)
        at compojure.core$if_route$fn__1751.invoke(core.clj:41)
        at compojure.core$if_method$fn__1743.invoke(core.clj:27)
        at compojure.core$routing$fn__1786.invoke(core.clj:144)
        at clojure.core$some.invoke(core

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/86340292873337/f
---[aa]

**Comment by braid-sync** [comment]
this works locally; I’m wondering if it’s due to the clojars outage yesterday; maybe the deployed jar is missing some classes?

[--- Commented from Asana.com
#commenter James Cash
---[aa]
